name: Deploy to Azure

on:
  push:
    branches:
      - main
      - nx-cloud-setup

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build applications
        run: |
          npx nx build host --configuration=production --skip-nx-cache
          npx nx build productsRemote --configuration=production --skip-nx-cache
          npx nx build productDetailRemote --configuration=production --skip-nx-cache

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/apps/host
            dist/apps/productsRemote
            dist/apps/productDetailRemote
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Host
        run: |
          ls -la
          cd dist/apps/host
          zip -r host.zip *
          az webapp deployment source config-zip --name nxstore-host --resource-group nx-store-demo-rg --src host.zip

      - name: Deploy Products Remote
        run: |
          cd dist/apps/productsRemote
          zip -r products.zip *
          az webapp deployment source config-zip --name nxstore-products --resource-group nx-store-demo-rg --src products.zip

      - name: Deploy Product Detail Remote
        run: |
          cd dist/apps/productDetailRemote
          zip -r detail.zip *
          az webapp deployment source config-zip --name nxstore-productdetail --resource-group nx-store-demo-rg --src detail.zip

      - name: Azure logout
        run: az logout
